algoritmo "Multiplicação"
// Função : Multiplicar 2 Nºs
// Autor : Carlos Gabriel
// Data : 19/05/2021
// Seção de Declarações 
var
   num1, num2:inteiro
   produto: real
inicio
// Seção de Comandos 
   escreva("Diga o 1º nº a ser multiplicado")
   leia(num1)
   escreva("Diga o 2º nº a ser multiplicado")
   leia(num2)
   produto <- num1 * num2
   escreva(num1," x ", num2," = ", produto)
fimalgoritmo
