algoritmo "Fahrenheit p/ celsius"
// Função : Transformar de Fahrenheit p/ celsius
// Autor : Carlos Gabriel
// Data : 07/03/2021
var
   cels, fah:real
inicio
   // Seção de Comandos
      escreval("Fale a Temperatura em Fahrenheit de onde vc tá:")
      leia(fah)

   // Seção de Declarações
      cels <- ((fah - 32) / 1.8)

   // Seção de Comandos 2
      escreval("É ", cels,"º Celsius")

fimalgoritmo
