algoritmo "Celsius p/ fahrenheit"
// Função : Transformar de Celsius p/ fahrenheit
// Autor : Carlos Gabriel
// Data : 07/03/2021
var
   cels, fah:real
inicio
   // Seção de Comandos
      escreval("Fale a Temperatura em Celsius de onde vc tá:")
      leia(cels)
      
   // Seção de Declarações
      fah <- (9 * cels / 5 + 32)
      
   // Seção de Comandos 2
      escreval("É ", fah," em Fahrenheit")
      
fimalgoritmo
